
events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;

	server {
		listen 3000 ssl;

		ssl_certificate	 /etc/nginx/ssl/certificate.cert;
		ssl_certificate_key /etc/nginx/ssl/private.key;

		location / {
			proxy_pass http://main_app:3000;
		}
	}

	server {
		listen 3001 ssl;

		ssl_certificate	 /etc/nginx/ssl/certificate.cert;
		ssl_certificate_key /etc/nginx/ssl/private.key;

		location / {
			proxy_pass http://public_api:3001;
		}
	}

	server {
		listen 3002 ssl;

		ssl_certificate	 /etc/nginx/ssl/certificate.cert;
		ssl_certificate_key /etc/nginx/ssl/private.key;

		location / {
			proxy_pass http://avatar_server:80;
		}
	}

}
