
services:
  main_app:
    build: ./services/main_app
    image: main_app:ft_transcendence
    container_name: main_app
    ports:
      - 3000:3000
    networks:
      - my_network
    depends_on:
      - mariadb
    volumes:
      - avatar:/app/public/avatars

  public-api:
    build: ./services/public-api
    image: public-api:ft_transcendence
    container_name: public-api
    ports:
      - 3001:3001
    networks:
      - my_network
    depends_on:
      - mariadb

  mariadb:
    build: ./services/mariadb
    image: mariadb:ft_transcendence
    container_name: mariadb
    networks:
      - my_network
    volumes:
      - db:/var/lib/mysql

  avatar_server:
    build: ./services/avatar_server
    image: avatar_server:ft_transcendence
    container_name: avatar_server
    ports:
      - 3002:80
    networks:
      - my_network
    volumes:
      - avatar:/avatars

networks:
  my_network: 

volumes:
  avatar: 
  db: 
