
services:
  main_app:
    build: ./services/main_app
    image: main_app:ft_transcendence
    container_name: main_app
    networks:
      - my_network
    depends_on:
      - mariadb
    volumes:
      - avatar:/app/public/avatars
    env_file: ./services/main_app/.env

  public_api:
    build: ./services/public_api
    image: public_api:ft_transcendence
    container_name: public_api
    networks:
      - my_network
    depends_on:
      - mariadb
    env_file: ./services/public_api/.env

  mariadb:
    build: ./services/mariadb
    image: mariadb:ft_transcendence
    container_name: mariadb
    networks:
      - my_network
    volumes:
      - db:/var/lib/mysql
    env_file: ./services/mariadb/.env

  avatar_server:
    build: ./services/avatar_server
    image: avatar_server:ft_transcendence
    container_name: avatar_server
    networks:
      - my_network
    volumes:
      - avatar:/avatars

  reverse_proxy:
    build: ./services/reverse_proxy
    image: reverse_proxy:ft_transcendence
    container_name: reverse_proxy
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    networks:
      - my_network
    depends_on:
      - main_app
      - public_api
      - avatar_server

networks:
  my_network: 

volumes:
  avatar: 
  db: 
